// Generated by `pnpm db:types` from db/migrations — do not edit by hand.
export type Json = string | number | boolean | null | Json[] | { [key: string]: Json | undefined };

export type Enums = {
  age_band: "18-24" | "25-34" | "35-44" | "45-54" | "55-64" | "65+";
  gender_band: "f" | "m" | "x";
  prophecy_status: "open" | "closed" | "resolved" | "void";
  question_type: "choice" | "meta";
  round_kind: "anchor" | "weekly" | "flash";
  round_status: "draft" | "live" | "closed";
  settlement_band: "city" | "town" | "rural";
  trust_level: "anon" | "verified";
};

export type Tables = {
  agg_option_country: {
    round_id: string;
    question_id: string;
    option_id: string;
    country_code: string;
    trust: Enums["trust_level"];
    cnt: number;
    sum_weight: number;
  };
  answers: {
    id: string;
    submission_id: string;
    question_id: string;
    option_id: string;
  };
  auth_sessions: {
    id: string;
    voter_id: string;
    auth_user_id: string;
    created_at: string;
    expires_at: string;
  };
  auth_users: {
    id: string;
    provider: string;
    subject_hash: string;
    created_at: string;
  };
  contradiction_pairs: {
    id: string;
    round_id: string;
    key: string;
    option_a_id: string;
    option_b_id: string;
    i18n: Json;
    active: boolean;
  };
  country_population: {
    country_code: string;
    name_en: string;
    region: string | null;
    population: number;
    demographics: Json;
    source: string;
    updated_at: string;
  };
  country_stats: {
    round_id: string;
    country_code: string;
    submissions_count: number;
    verified_count: number;
    unlocked: boolean;
    insufficient_sample: boolean;
    survival_index: number | null;
    contradiction_index: number | null;
    realism_mean: number | null;
    compromise_mean: number | null;
    axis_means: Json;
    archetype_shares: Json;
    contradiction_shares: Json;
    top_archetype: string | null;
    titles: string[];
    rank: number | null;
    computed_at: string;
  };
  job_leases: {
    name: string;
    locked_until: string | null;
    last_run_at: string | null;
    last_status: string | null;
    last_error: string | null;
  };
  meta_guesses: {
    id: string;
    submission_id: string;
    question_id: string;
    guess: number;
    actual_at_submit: number | null;
    actual_final: number | null;
  };
  narrator_posts: {
    id: string;
    round_id: string | null;
    locale: string;
    body: string;
    model: string | null;
    context: Json;
    approved: boolean;
    generated_at: string;
    published_at: string | null;
  };
  options: {
    id: string;
    question_id: string;
    key: string;
    position: number;
    i18n: Json;
    icon: string | null;
    axis_weights: Json;
    compromise: boolean;
    honeypot: boolean;
    active: boolean;
  };
  planet_snapshots: {
    id: number;
    round_id: string;
    at: string;
    votes_total: number;
    survival_raw: number | null;
    survival_weighted: number | null;
    contradiction_weighted: number | null;
    pulse_per_min: number;
  };
  planet_stats: {
    round_id: string;
    votes_total: number;
    votes_verified: number;
    votes_flagged: number;
    countries_unlocked: number;
    survival_raw: number | null;
    survival_weighted: number | null;
    contradiction_raw: number | null;
    contradiction_weighted: number | null;
    realism_mean: number | null;
    compromise_mean: number | null;
    consistency_mean: number | null;
    axis_means: Json;
    archetype_shares: Json;
    contradiction_shares: Json;
    pulse_per_min: number;
    pulse_refreshed_at: string;
    computed_at: string;
  };
  prophecies: {
    id: string;
    key: string;
    i18n: Json;
    category: string | null;
    opens_at: string;
    closes_at: string;
    resolves_at: string;
    status: Enums["prophecy_status"];
    outcome: boolean | null;
    resolved_at: string | null;
    resolution_note: string | null;
    review_required: boolean;
    active: boolean;
    created_at: string;
    updated_at: string;
  };
  prophecy_guesses: {
    id: string;
    prophecy_id: string;
    voter_id: string;
    probability: number;
    trust: Enums["trust_level"];
    country_code: string | null;
    ip_hash: string;
    locale: string;
    brier: number | null;
    flagged: boolean;
    flag_reasons: string[];
    created_at: string;
  };
  pulse_buckets: {
    round_id: string;
    minute: string;
    cnt: number;
  };
  questions: {
    id: string;
    round_id: string;
    key: string;
    type: Enums["question_type"];
    position: number;
    i18n: Json;
    meta_target_question_id: string | null;
    meta_target_option_id: string | null;
    review_required: boolean;
    anchor: boolean;
    active: boolean;
  };
  rounds: {
    id: string;
    slug: string;
    kind: Enums["round_kind"];
    status: Enums["round_status"];
    starts_at: string;
    ends_at: string | null;
    unlock_threshold: number;
    survival_weights: Json;
    i18n: Json;
    created_at: string;
    updated_at: string;
  };
  submissions: {
    id: string;
    round_id: string;
    voter_id: string;
    auth_user_id: string | null;
    trust: Enums["trust_level"];
    country_code: string | null;
    geo_country_code: string | null;
    declared_country: string | null;
    age_band: Enums["age_band"] | null;
    gender: Enums["gender_band"] | null;
    settlement: Enums["settlement_band"] | null;
    ip_hash: string;
    ua_family: string | null;
    locale: string;
    axis_scores: Json;
    realism: number | null;
    consistency: number | null;
    compromise: number | null;
    survival: number | null;
    archetype: string | null;
    contradictions_hit: string[];
    weight: number;
    flagged: boolean;
    flag_reasons: string[];
    loaded_at: string | null;
    submitted_at: string;
    synthetic: boolean;
  };
  voters: {
    id: string;
    anon_id: string;
    auth_user_id: string | null;
    trust: Enums["trust_level"];
    first_seen_at: string;
    last_seen_at: string;
  };
};

export type TableName = keyof Tables;
export type Row<T extends TableName> = Tables[T];
