import "./_env";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { createPgliteExecutor } from "@/lib/db/pglite";
import { runMigrations } from "@/lib/db/migrate";
import type { DbExecutor } from "@/lib/db/executor";

/**
 * pnpm db:types — generates src/types/database.ts from the migrated schema
 * (an in-memory PGlite with all migrations applied, so it never depends on a remote DB).
 */
type Col = { table_name: string; column_name: string; data_type: string; udt_name: string; is_nullable: "YES" | "NO"; ordinal_position: number };
type EnumRow = { enum_name: string; labels: string[] };

function tsType(c: Col, enums: Set<string>): string {
  const base = (() => {
    if (enums.has(c.udt_name)) return `Enums["${c.udt_name}"]`;
    if (c.data_type === "ARRAY") {
      const inner = c.udt_name.replace(/^_/, "");
      if (enums.has(inner)) return `Enums["${inner}"][]`;
      return inner === "text" || inner === "varchar" || inner === "uuid" ? "string[]" : "unknown[]";
    }
    switch (c.udt_name) {
      case "uuid":
      case "text":
      case "varchar":
      case "bpchar":
      case "timestamptz":
      case "timestamp":
      case "date":
        return "string";
      case "int2":
      case "int4":
      case "int8":
      case "numeric":
      case "float4":
      case "float8":
        return "number";
      case "bool":
        return "boolean";
      case "jsonb":
      case "json":
        return "Json";
      default:
        return "unknown";
    }
  })();
  return c.is_nullable === "YES" ? `${base} | null` : base;
}

async function generate(db: DbExecutor): Promise<string> {
  const enums = await db.query<EnumRow>(
    `select t.typname as enum_name, array_agg(e.enumlabel order by e.enumsortorder) as labels
     from pg_type t join pg_enum e on e.enumtypid = t.oid group by t.typname order by t.typname`,
  );
  const cols = await db.query<Col>(
    `select table_name, column_name, data_type, udt_name, is_nullable, ordinal_position
     from information_schema.columns where table_schema = 'public' order by table_name, ordinal_position`,
  );
  const enumNames = new Set(enums.map((e) => e.enum_name));
  const tables = new Map<string, Col[]>();
  for (const c of cols) {
    if (c.table_name === "schema_migrations") continue;
    tables.set(c.table_name, [...(tables.get(c.table_name) ?? []), c]);
  }
  let out = `// Generated by \`pnpm db:types\` from db/migrations — do not edit by hand.\n`;
  out += `export type Json = string | number | boolean | null | Json[] | { [key: string]: Json | undefined };\n\n`;
  out += `export type Enums = {\n`;
  for (const e of enums) out += `  ${e.enum_name}: ${e.labels.map((l) => JSON.stringify(l)).join(" | ")};\n`;
  out += `};\n\n`;
  out += `export type Tables = {\n`;
  for (const [name, list] of tables) {
    out += `  ${name}: {\n`;
    for (const c of list) out += `    ${c.column_name}: ${tsType(c, enumNames)};\n`;
    out += `  };\n`;
  }
  out += `};\n\nexport type TableName = keyof Tables;\nexport type Row<T extends TableName> = Tables[T];\n`;
  return out;
}

async function main() {
  const db = await createPgliteExecutor();
  await runMigrations(db);
  const ts = await generate(db);
  const target = resolve(process.cwd(), "src/types/database.ts");
  writeFileSync(target, ts);
  console.log(`wrote ${target}`);
  await db.close();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
